name: MedAssist Build
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
    
      - name: Install Dependencies
        run: |
          cd midassist
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Apply Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run Tests
        run: |
          python manage.py test core
