name: MedAssist Build
on: push
jobs: 
  setup-mongodb:
    runs-on: ubuntu-latest
    steps:
      - name: Install MongoDB
        run: |
          sudo apt update
          sudo apt install -y gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
          sudo apt update
          sudo apt install -y mongodb-org
          sudo systemctl start mongod
          sudo systemctl enable mongod
          sudo systemctl status mongod
          
  build:
    needs: setup-mongodb
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Apply Migrations
        run: |
          cd midassist
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests
        run: |
          python manage.py test core
